baseURL = 'https://christernilsson.github.io/SrS/'
languageCode = 'sv-se'
title = 'SrS'
default_auto = false
publishDir = "docs"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
